# Generated by Django 4.2 on 2025-12-07 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('EXERCISE', 'Physical Exercise'), ('FOOD', 'Food Intake')], max_length=20)),
                ('sleep_hours', models.FloatField(default=0.0)),
                ('water_intake', models.FloatField(default=0.0)),
                ('exercise_type', models.CharField(blank=True, max_length=50, null=True)),
                ('calories_burned', models.IntegerField(default=0)),
                ('calories_intake', models.IntegerField(default=0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fats', models.FloatField(default=0.0)),
                ('health_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
