# Generated by Django 4.2 on 2025-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthlog',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='carbs',
            field=models.FloatField(default=0.0, help_text='Grams'),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('Running', 'Jogging / Running'), ('Gym', 'Gym / Weights'), ('Sport', 'Sports (Football, Tennis, etc)'), ('Yoga', 'Yoga'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='fats',
            field=models.FloatField(default=0.0, help_text='Grams'),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='protein',
            field=models.FloatField(default=0.0, help_text='Grams'),
        ),
    ]
